language: python
before_script:
  - sleep 3
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pylint

# Command to run tests, e.g. python setup.py test
script:
- pylint tests/*.py
#- pytest test_space.py
